// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
let _VERSION = '0.0.0'; // This value will be overwritten by webpack
let _DEBUG_INFO_ENABLED = true; // This value will be overwritten by webpack
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;
export const APP_DOMAIN = 'app1.com';
export const APP_PORT = 9000;
export const AUTH0_CLIENT_ID = 'ELcIRSOP0eWDLpkQtOWf5SH3DfLssrDJ';
export const AUTH0_DOMAIN = 'lkybstrd.auth0.com';
